resource_group_name = "rg-cid-nodeapp"
location            = "eastus"
app_name            = "cid-nodeapp"
github_repo_url     = "https://github.com/iarunesh/CID_Scanning"
github_branch       = "main"
